# Generated by Django 4.2.2 on 2023-06-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_server', '0002_data_loading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
