# Generated by Django 4.2.2 on 2023-06-24 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_server', '0003_alter_comments_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(help_text='Ссылка на новость, к которой написан комментарий', on_delete=django.db.models.deletion.CASCADE, to='news_server.news'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(help_text='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(help_text='Автор новости', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Дата создания новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Заголовок новости', max_length=255),
        ),
    ]
