version: "3.9"

services:
  db_itfox:    
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_db: